In [1]:
print("a")

a


Merhaba

herhangi başka şeyler de yazılabilir

_italik_
**kalin**

In [2]:
"a"

'a'

---

# Numpy Giriş

- Numerical Python
- Bilimsel hesaplamalar için kullanılır.
- Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
- Listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır. Listelerdeki tutulan tüm öğeler için ayrı ayrı tip bilgisi ve ek bilgiler tutulur, numpy'da ise kullanılacak veri tipleri arasında bir ayrım yoktur, numpy hepsini fixed type(sabitlenmiş tipe) zorlar(hepsinin tipi aynı olacak yani)  bu sayede tek bir tip bilgisi tutar, bu şekilde numpy daha az maliyetlidir. Bu sayede veri saklama anlamında çok ciddi performans sağlar.
![numpy array yapısı](img/numpy-001.png)

## Neden NumPy?
- NumPy'ı daha üst seviyeden, daha az çabayla, daha büyük işler yapabilme olanağı sağladığından dolayı kullanıyor olacağız.
- Yer tutma maliyetlerini NumPy çok azaltmaktadır.

In [8]:
a = [1,2,3,4]
b = [2,3,4,5]
a
b # sadece en son ne yazdıysak onu yazdırır

[2, 3, 4, 5]

In [9]:
a

[1, 2, 3, 4]

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4]) # numpy array veri tipinde
b = np.array([2,3,4,5])

In [12]:
a * b

array([ 2,  6, 12, 20])

## Numpy Array Oluşturmak
- Sıfırdan veya listeler üzerinde NumPy Array oluşturulabilir.

Numpy array, numpy kütüphanesi içerisinde yer alan veri tipidir (listeler, tuple ve sözlükler gibi). 

In [15]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [16]:
np.array([3.14, 4, 2, 13]) #sabit tip baskısı - NumPy array tek tip veri tutar. 
                           #Böylece bir tane veri tutar ve veri tutma maliyeti düşürülür

array([ 3.14,  4.  ,  2.  , 13.  ])

In [19]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

## Sıfırdan array oluşturma

In [17]:
np.zeros(10, dtype = int) # 0 lardan oluşan int tipinde nd array oluştur.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((3,5), dtype= int)  # iki boyutlu 1lerden oluşan nd array oluştur.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.full((3,5), 3) # Sadece 3lerden oluşan ve bizim verdiğimiz boyut bilgisiyle oluşan array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [28]:
np.arange(0,31,3) # 0'dan 31'e kadar 3er 3er artacak bir dizi oluşturmak 
                  # arange fonksiyonunu çok sık kullanacağız.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [29]:
np.linspace(0, 1, 10) # O ile 1 arasında 10 tane değer oluştur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [30]:
np.random.normal(10, 4, (3,4)) # Ortalaması 10, Standart sapması 4 olan 2 boyutlu (3e4) random array oluştur.
                               # random.normal fonksiyonunu çok sık kullanacağız.

array([[ 7.25146931,  6.8703473 ,  3.94723798,  4.42124934],
       [18.91699769, 12.77242545, 12.43752782, 20.54370614],
       [15.51037639, 12.84345899,  9.57200393, 15.94204809]])

- Tek boyutlu array'ın karşılığı **Vektör** dür.
- İki boyutlu array'ın karşılığı **Matris** dir.

In [31]:
np.random.randint(0, 10, (3,3)) # Dağılımla ilgilenmiyorum, integer değerlerden rastgele oluşmuş bir array
                                # O'dan 10'a kadar 3e3lük bir random matris oluştur.
                                # random.randint fonksiyonunu çok sık kullanacağız.

array([[7, 1, 5],
       [1, 0, 1],
       [8, 1, 3]])

## NumPy Array Özellikleri

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [127]:
import numpy as np

In [128]:
np.random.randint(10, size = 10)

array([6, 5, 4, 7, 3, 9, 9, 7, 5, 9])

In [129]:
a = np.random.randint(10, size = 10)

In [130]:
a

array([1, 2, 9, 1, 4, 8, 5, 9, 9, 0])

In [131]:
a.ndim

1

In [132]:
a.shape

(10,)

In [133]:
a.size

10

In [134]:
a.dtype

dtype('int32')

In [48]:
b = np.random.randint(10, size = (3,5))

In [49]:
b

array([[7, 6, 4, 1, 8],
       [4, 3, 4, 8, 5],
       [5, 4, 3, 6, 8]])

In [50]:
b.ndim

2

In [51]:
b.shape

(3, 5)

In [52]:
b.size

15

In [53]:
b.dtype

dtype('int32')

## Yeniden Şekillendirme(reshaping)

In [54]:
import numpy as np

In [55]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Bu array üzerinden 3e3lük array oluşturalım: 

Bazen çalışmalarda fonksiyonların veya döngülerin üretmiş olduğu çıktılar tek bir boyutta(tek bir array formunda) gerçekleşebiliyor. Bunları bazen tek boyuttan iki boyuta, bazen de iki boyuttan tek boyuta indirilme ihtiyacları ortaya çıkabiliyor. Bu sebeple bu yapısal dönüşümleri iyi kavramak gerekir. Buna benzer ihtiyaçlarla **reshape** fonksiyonuyla başa çıkabiliyoruz

In [57]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a = np.arange(1,10)

In [59]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a.ndim

1

In [62]:
b = a.reshape((1,9)) # tek satır 9 sütun | artık bir matristir, array değil.

In [63]:
b.ndim

2

## Array Birleştirme (Concatenation)

In [64]:
import numpy as np

In [65]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [70]:
# Tek boyut

In [67]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [68]:
z = np.array([7,8,9])

In [69]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
# İki boyut

In [72]:
a = np.array([[1,2,3],
              [4,5,6]])

In [73]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
np.concatenate([a,a], axis = 1) # Satır bazında değil sütun bazında

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [75]:
np.concatenate([a,a], axis = 0) # Sütun bazında değil satır bazında birleştirir.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

## Array Ayırma (Splitting)

In [79]:
import numpy as np

In [81]:
x = np.array([1,2,3,99,99,3,2,1])

In [83]:
np.split(x, [3,5]) # 3'e kadar olan(indeks sayısına göre) ve 5'e kadar olan arrayleri ayır

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [84]:
a,b,c = np.split(x, [3,5])

In [85]:
a

array([1, 2, 3])

In [86]:
b

array([99, 99])

In [87]:
c

array([3, 2, 1])

### İki boyutlu ayırma

In [88]:
m = np.arange(16).reshape(4,4)

In [89]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [91]:
ust, alt = np.vsplit(m, [2])

In [92]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [93]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [96]:
sag, sol = np.hsplit(m,[2])

In [97]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [98]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Sıralama (Sorting)

In [99]:
import numpy as np

In [100]:
v = np.array([2,1,4,3,5])

In [101]:
v

array([2, 1, 4, 3, 5])

In [102]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [103]:
v

array([2, 1, 4, 3, 5])

In [104]:
v.sort()

In [105]:
v

array([1, 2, 3, 4, 5])

np.sort(v), sort metodu, numpy'ın içerisinden çağırıldığında veri setinin ortajinal yapısını bozmadı.
Eğer biz sıralanmış yöntemini kullanmak istersek **yeniden atama** yöntemiyle kullanabiliriz.

v.sort() fonksiyonu v nin yapısını bozmuş oldu. 

In [107]:
# iki boyutlu array siralama

In [110]:
m = np.random.normal(20,5 , (3,3))

In [111]:
m

array([[19.10382114, 17.90207181, 15.60421162],
       [27.40092578,  7.7515947 , 22.33864445],
       [ 5.35316166, 26.57178411, 23.76979085]])

In [113]:
np.sort(m, axis = 1) # her bir satırı kendi içerisinde küçükten büyüğe sıralamıştır.

array([[15.60421162, 17.90207181, 19.10382114],
       [ 7.7515947 , 22.33864445, 27.40092578],
       [ 5.35316166, 23.76979085, 26.57178411]])

In [115]:
np.sort(m, axis = 0) # her bir sütunu kendi içerisinde küçükten büyüğe sıralamıştır.

array([[ 5.35316166,  7.7515947 , 15.60421162],
       [19.10382114, 17.90207181, 22.33864445],
       [27.40092578, 26.57178411, 23.76979085]])

Bilgiler:
- NumPy array'in boyut bilgisini **shape** metodu verir.
- NumPy array'in boyut sayısını **ndim** metodu verir.
- NumPy array'in toplam eleman sayısını **size** metodu verir.
- NumPy array'in veri tipi bilgisini **dtype** metodu verir.

import numpy as np

In [118]:
np.random.randint(10, size = (3,3,2))

array([[[4, 0],
        [9, 1],
        [6, 5]],

       [[3, 0],
        [2, 5],
        [1, 3]],

       [[1, 1],
        [6, 7],
        [4, 0]]])

---

## Index ile Elemana Erişmek

In [136]:
import numpy as np 
a = np.random.randint(10, size = 10)
a

array([1, 7, 2, 2, 5, 5, 8, 8, 4, 4])

In [137]:
a[0] # klasik kullanım

1

In [138]:
a[0] = 100

In [140]:
a

array([100,   7,   2,   2,   5,   5,   8,   8,   4,   4])

In [141]:
m = np.random.randint(10, size = (3,5))
m

array([[7, 3, 6, 0, 8],
       [3, 3, 4, 7, 4],
       [8, 5, 2, 3, 7]])

In [142]:
m[0,0]

7

In [143]:
m[1,1]

3

In [144]:
m[1,4]

4

In [145]:
m[1, 4] = 99

In [146]:
m

array([[ 7,  3,  6,  0,  8],
       [ 3,  3,  4,  7, 99],
       [ 8,  5,  2,  3,  7]])

In [149]:
m[1,4] = 2.2 # NumPy Arrayler fixed type'tır. 2.2  array int olduğu için 2 olarak alınır.

In [148]:
m

array([[7, 3, 6, 0, 8],
       [3, 3, 4, 7, 2],
       [8, 5, 2, 3, 7]])

## Array Alt Küme İşlemleri(Slicing)

In [150]:
import numpy as np

In [152]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [153]:
a[0:3]

array([20, 21, 22])

In [154]:
a[:3]

array([20, 21, 22])

In [155]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [157]:
a[1::2]  # 2. : işaretinden sonra seçilecek sayıların amacı indeksleri kaçar kaçar atlayacağını belirtmektir.

array([21, 23, 25, 27, 29])

In [158]:
a[0::2]

array([20, 22, 24, 26, 28])

In [159]:
a[0::3]

array([20, 23, 26, 29])

In [160]:
# İki boyutlu slice işlemleri

In [161]:
m = np.random.randint(10, size = (5,5))

In [162]:
m

array([[5, 3, 8, 1, 9],
       [3, 5, 3, 8, 9],
       [2, 5, 2, 8, 8],
       [2, 7, 2, 5, 7],
       [0, 3, 3, 7, 0]])

In [164]:
m[:,0] # Bütün satırlar arasından, 0. sütunu seç.

array([5, 3, 2, 2, 0])

In [165]:
m[:,1]

array([3, 5, 5, 7, 3])

In [167]:
m[0,:] # Tüm sütunlar arasından 0. satır.

array([5, 3, 8, 1, 9])

In [169]:
m[0] # 0. satır olarak algılar.

array([5, 3, 8, 1, 9])

In [170]:
m[0:2, 0:3]

array([[5, 3, 8],
       [3, 5, 3]])

In [171]:
m[::,:2]

array([[5, 3],
       [3, 5],
       [2, 5],
       [2, 7],
       [0, 3]])

In [172]:
m[1:3, 0:2]

array([[3, 5],
       [2, 5]])

## Alt Küme Üzerinde İşlem Yapmak

In [174]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[4, 6, 6, 2, 5],
       [5, 1, 9, 2, 4],
       [5, 3, 9, 5, 7],
       [4, 2, 7, 4, 7],
       [8, 0, 6, 4, 2]])

Bir array'in alt kümesine eriştikten sonra isimlendirip kaydettiğimizi düşünelim, bu kaydetmiş olduğumuz isimlendirme üzerine bir değişiklik yaptığımızda array'in ilk halinde de değişiklik olmakta. Fakat bazen seçilen arrayin alt kümesi üzerinde, o alt kümeye özel işlemler yapılmak istenebilir. Bu durumda **alt kümeleri bağımsızlaştırmak** denilen bir işlem yaparız.

In [175]:
alt_a = a[0:3,0:2]

In [176]:
alt_a

array([[4, 6],
       [5, 1],
       [5, 3]])

In [179]:
alt_a[0,0] = 99
alt_a[1,1] = 888

In [180]:
a

array([[ 99,   6,   6,   2,   5],
       [  5, 888,   9,   2,   4],
       [  5,   3,   9,   5,   7],
       [  4,   2,   7,   4,   7],
       [  8,   0,   6,   4,   2]])

In [181]:
m = np.random.randint(10, size = (5,5))
m

array([[8, 8, 4, 6, 3],
       [3, 0, 8, 2, 4],
       [4, 6, 9, 4, 9],
       [7, 1, 0, 7, 5],
       [7, 4, 1, 0, 3]])

In [183]:
alt_b = m[0:3,0:2].copy()
alt_b

array([[8, 8],
       [3, 0],
       [4, 6]])

In [184]:
alt_b[0,0] = 999

In [185]:
alt_b

array([[999,   8],
       [  3,   0],
       [  4,   6]])

In [186]:
m

array([[8, 8, 4, 6, 3],
       [3, 0, 8, 2, 4],
       [4, 6, 9, 4, 9],
       [7, 1, 0, 7, 5],
       [7, 4, 1, 0, 3]])

## Fancy Index ile Elemanlara Erişmek

Fancy Index kavramı ileride en önemli anlamlardan biri olacak. Pandas'da ve NumPy'da Daha ileri düzey eleman seçme kabiliyeti verir.

In [187]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [188]:
v[1]

3

In [189]:
v[3]

9

In [190]:
v[5]

15

In [191]:
[v[1], v[3], v[5]]

[3, 9, 15]

Elimizde onlarca, belki yüzlerce, binlerce index olduğunda bu index değerlerini 1 kerede sorgulama işlemlerini nasıl yapıyoruz?

In [192]:
al_getir = [1,3,5]

In [193]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [195]:
v[al_getir] # 1. 3. 5. indeksi getirdi. Buna Fancy Index denir.

array([ 3,  9, 15])

In [196]:
# İki boyutta fancy

In [197]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [199]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [200]:
m[satir, sutun]

array([1, 5])

In [201]:
# Basit İndex ile fancy index

In [202]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [203]:
m[0, [1,2]]

array([1, 2])

In [206]:
# slice ile fancy

In [205]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

---

## KOŞULLU ELEMAN İŞLEMLERİ
Belirli bir array veya matrisde, belirli koşulları sağlayan elemanlar.

In [1]:
import numpy as np
v = np.array([1,2,3,4,5])

In [2]:
v < 3

array([ True,  True, False, False, False])

In [4]:
v[v < 3] # fancy index

array([1, 2])

In [5]:
v[v > 3]

array([4, 5])

In [6]:
v[v >= 3]

array([3, 4, 5])

In [7]:
v[v <= 3]

array([1, 2, 3])

In [8]:
v[v == 3]

array([3])

In [9]:
v[v != 3]

array([1, 2, 4, 5])

In [10]:
v

array([1, 2, 3, 4, 5])

In [11]:
v*2

array([ 2,  4,  6,  8, 10])

In [12]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [13]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [14]:
v**2

array([ 1,  4,  9, 16, 25])

## MATEMATİKSEL İŞLEMLER

In [15]:
import numpy as np
v = np.array([1,2,3,4,5])

In [16]:
v - 1

array([0, 1, 2, 3, 4])

In [17]:
v * 5

array([ 5, 10, 15, 20, 25])

In [18]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

### ufunc 
- ufuncs "Evrensel Fonksiyonlar" anlamına gelir ve ndarray nesnesi üzerinde çalışan NumPy fonksiyonlarıdır.
- ufuncs, NumPy'de elemanlar üzerinde yinelemeden çok daha hızlı olan vektörleştirmeyi uygulamak için kullanılır. Ayrıca yayın ve hesaplama için çok yararlı olan reduce, accumulate vb. gibi ek yöntemler sağlarlar.
- Biz matematiksel operatörleri kullanıp işlemler yapsakta, arka tarafta numpy içerisinde tanımlanmış spesifik fonksiyonlar çalıştırılır. 

In [ ]:
np.subtract(v, 1) # v - 1

In [25]:
np.add(v, 1) # v + 1

array([2, 3, 4, 5, 6])

In [26]:
np.multiply(v , 4) # v * 4

array([ 4,  8, 12, 16, 20])

In [27]:
np.divide(v, 3) # v / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [28]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [30]:
np.power(v, 3) # v**3

array([  1,   8,  27,  64, 125], dtype=int32)

v % 2

In [32]:
np.mod(v,2) # v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [34]:
np.absolute(np.array([-3])) # |v| mutlak değer

array([3])

In [35]:
np.sin(360)

0.9589157234143065

In [36]:
np.cos(180)

-0.5984600690578581

In [37]:
v = np.array([1,2,3])

In [38]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [39]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [40]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [41]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\tahaa\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\tahaa\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [42]:
# cheatsheetlere bakın

## NumPy ile iki Bilinmeyenli Denklem Çözümü

In [45]:
import numpy as np

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

In [47]:
# Bilinmeyen ifadeleri katsayılarını bir vektöre koy, sonuçları bir vektöre koy.
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [48]:
a

array([[5, 1],
       [1, 3]])

In [49]:
b

array([12, 10])

In [50]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

---