In [1]:
print("a")

a


Merhaba

herhangi başka şeyler de yazılabilir

_italik_
**kalin**

In [2]:
"a"

'a'

---

# Numpy Giriş

- Numerical Python
- Bilimsel hesaplamalar için kullanılır.
- Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
- Listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır. Listelerdeki tutulan tüm öğeler için ayrı ayrı tip bilgisi ve ek bilgiler tutulur, numpy'da ise kullanılacak veri tipleri arasında bir ayrım yoktur, numpy hepsini fixed type(sabitlenmiş tipe) zorlar(hepsinin tipi aynı olacak yani)  bu sayede tek bir tip bilgisi tutar, bu şekilde numpy daha az maliyetlidir. Bu sayede veri saklama anlamında çok ciddi performans sağlar.
![numpy array yapısı](img/numpy-001.png)

## Neden NumPy?
- NumPy'ı daha üst seviyeden, daha az çabayla, daha büyük işler yapabilme olanağı sağladığından dolayı kullanıyor olacağız.
- Yer tutma maliyetlerini NumPy çok azaltmaktadır.

In [8]:
a = [1,2,3,4]
b = [2,3,4,5]
a
b # sadece en son ne yazdıysak onu yazdırır

[2, 3, 4, 5]

In [9]:
a

[1, 2, 3, 4]

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4]) # numpy array veri tipinde
b = np.array([2,3,4,5])

In [12]:
a * b

array([ 2,  6, 12, 20])

## Numpy Array Oluşturmak
- Sıfırdan veya listeler üzerinde NumPy Array oluşturulabilir.

Numpy array, numpy kütüphanesi içerisinde yer alan veri tipidir (listeler, tuple ve sözlükler gibi). 

In [15]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [16]:
np.array([3.14, 4, 2, 13]) #sabit tip baskısı - NumPy array tek tip veri tutar. 
                           #Böylece bir tane veri tutar ve veri tutma maliyeti düşürülür

array([ 3.14,  4.  ,  2.  , 13.  ])

In [19]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

## Sıfırdan array oluşturma

In [17]:
np.zeros(10, dtype = int) # 0 lardan oluşan int tipinde nd array oluştur.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((3,5), dtype= int)  # iki boyutlu 1lerden oluşan nd array oluştur.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.full((3,5), 3) # Sadece 3lerden oluşan ve bizim verdiğimiz boyut bilgisiyle oluşan array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [28]:
np.arange(0,31,3) # 0'dan 31'e kadar 3er 3er artacak bir dizi oluşturmak 
                  # arange fonksiyonunu çok sık kullanacağız.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [29]:
np.linspace(0, 1, 10) # O ile 1 arasında 10 tane değer oluştur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [30]:
np.random.normal(10, 4, (3,4)) # Ortalaması 10, Standart sapması 4 olan 2 boyutlu (3e4) random array oluştur.
                               # random.normal fonksiyonunu çok sık kullanacağız.

array([[ 7.25146931,  6.8703473 ,  3.94723798,  4.42124934],
       [18.91699769, 12.77242545, 12.43752782, 20.54370614],
       [15.51037639, 12.84345899,  9.57200393, 15.94204809]])

- Tek boyutlu array'ın karşılığı **Vektör** dür.
- İki boyutlu array'ın karşılığı **Matris** dir.

In [31]:
np.random.randint(0, 10, (3,3)) # Dağılımla ilgilenmiyorum, integer değerlerden rastgele oluşmuş bir array
                                # O'dan 10'a kadar 3e3lük bir random matris oluştur.
                                # random.randint fonksiyonunu çok sık kullanacağız.

array([[7, 1, 5],
       [1, 0, 1],
       [8, 1, 3]])