In [1]:
print("a")

a


Merhaba

herhangi başka şeyler de yazılabilir

_italik_
**kalin**

In [2]:
"a"

'a'

---

# Numpy Giriş

- Numerical Python
- Bilimsel hesaplamalar için kullanılır.
- Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
- Listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır. Listelerdeki tutulan tüm öğeler için ayrı ayrı tip bilgisi ve ek bilgiler tutulur, numpy'da ise kullanılacak veri tipleri arasında bir ayrım yoktur, numpy hepsini fixed type(sabitlenmiş tipe) zorlar(hepsinin tipi aynı olacak yani)  bu sayede tek bir tip bilgisi tutar, bu şekilde numpy daha az maliyetlidir. Bu sayede veri saklama anlamında çok ciddi performans sağlar.
![numpy array yapısı](img/numpy-001.png)

## Neden NumPy?
- NumPy'ı daha üst seviyeden, daha az çabayla, daha büyük işler yapabilme olanağı sağladığından dolayı kullanıyor olacağız.
- Yer tutma maliyetlerini NumPy çok azaltmaktadır.

In [8]:
a = [1,2,3,4]
b = [2,3,4,5]
a
b # sadece en son ne yazdıysak onu yazdırır

[2, 3, 4, 5]

In [9]:
a

[1, 2, 3, 4]

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4]) # numpy array veri tipinde
b = np.array([2,3,4,5])

In [12]:
a * b

array([ 2,  6, 12, 20])

## Numpy Array Oluşturmak
- Sıfırdan veya listeler üzerinde NumPy Array oluşturulabilir.

Numpy array, numpy kütüphanesi içerisinde yer alan veri tipidir (listeler, tuple ve sözlükler gibi). 

In [15]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
type(a)

numpy.ndarray

In [16]:
np.array([3.14, 4, 2, 13]) #sabit tip baskısı - NumPy array tek tip veri tutar. 
                           #Böylece bir tane veri tutar ve veri tutma maliyeti düşürülür

array([ 3.14,  4.  ,  2.  , 13.  ])

In [19]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

## Sıfırdan array oluşturma

In [17]:
np.zeros(10, dtype = int) # 0 lardan oluşan int tipinde nd array oluştur.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((3,5), dtype= int)  # iki boyutlu 1lerden oluşan nd array oluştur.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.full((3,5), 3) # Sadece 3lerden oluşan ve bizim verdiğimiz boyut bilgisiyle oluşan array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [28]:
np.arange(0,31,3) # 0'dan 31'e kadar 3er 3er artacak bir dizi oluşturmak 
                  # arange fonksiyonunu çok sık kullanacağız.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [29]:
np.linspace(0, 1, 10) # O ile 1 arasında 10 tane değer oluştur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [30]:
np.random.normal(10, 4, (3,4)) # Ortalaması 10, Standart sapması 4 olan 2 boyutlu (3e4) random array oluştur.
                               # random.normal fonksiyonunu çok sık kullanacağız.

array([[ 7.25146931,  6.8703473 ,  3.94723798,  4.42124934],
       [18.91699769, 12.77242545, 12.43752782, 20.54370614],
       [15.51037639, 12.84345899,  9.57200393, 15.94204809]])

- Tek boyutlu array'ın karşılığı **Vektör** dür.
- İki boyutlu array'ın karşılığı **Matris** dir.

In [31]:
np.random.randint(0, 10, (3,3)) # Dağılımla ilgilenmiyorum, integer değerlerden rastgele oluşmuş bir array
                                # O'dan 10'a kadar 3e3lük bir random matris oluştur.
                                # random.randint fonksiyonunu çok sık kullanacağız.

array([[7, 1, 5],
       [1, 0, 1],
       [8, 1, 3]])

## NumPy Array Özellikleri

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [127]:
import numpy as np

In [128]:
np.random.randint(10, size = 10)

array([6, 5, 4, 7, 3, 9, 9, 7, 5, 9])

In [129]:
a = np.random.randint(10, size = 10)

In [130]:
a

array([1, 2, 9, 1, 4, 8, 5, 9, 9, 0])

In [131]:
a.ndim

1

In [132]:
a.shape

(10,)

In [133]:
a.size

10

In [134]:
a.dtype

dtype('int32')

In [48]:
b = np.random.randint(10, size = (3,5))

In [49]:
b

array([[7, 6, 4, 1, 8],
       [4, 3, 4, 8, 5],
       [5, 4, 3, 6, 8]])

In [50]:
b.ndim

2

In [51]:
b.shape

(3, 5)

In [52]:
b.size

15

In [53]:
b.dtype

dtype('int32')

## Yeniden Şekillendirme(reshaping)

In [54]:
import numpy as np

In [55]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Bu array üzerinden 3e3lük array oluşturalım: 

Bazen çalışmalarda fonksiyonların veya döngülerin üretmiş olduğu çıktılar tek bir boyutta(tek bir array formunda) gerçekleşebiliyor. Bunları bazen tek boyuttan iki boyuta, bazen de iki boyuttan tek boyuta indirilme ihtiyacları ortaya çıkabiliyor. Bu sebeple bu yapısal dönüşümleri iyi kavramak gerekir. Buna benzer ihtiyaçlarla **reshape** fonksiyonuyla başa çıkabiliyoruz

In [57]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a = np.arange(1,10)

In [59]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a.ndim

1

In [62]:
b = a.reshape((1,9)) # tek satır 9 sütun | artık bir matristir, array değil.

In [63]:
b.ndim

2

## Array Birleştirme (Concatenation)

In [64]:
import numpy as np

In [65]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [70]:
# Tek boyut

In [67]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [68]:
z = np.array([7,8,9])

In [69]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
# İki boyut

In [72]:
a = np.array([[1,2,3],
              [4,5,6]])

In [73]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
np.concatenate([a,a], axis = 1) # Satır bazında değil sütun bazında

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [75]:
np.concatenate([a,a], axis = 0) # Sütun bazında değil satır bazında birleştirir.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

## Array Ayırma (Splitting)

In [79]:
import numpy as np

In [81]:
x = np.array([1,2,3,99,99,3,2,1])

In [83]:
np.split(x, [3,5]) # 3'e kadar olan(indeks sayısına göre) ve 5'e kadar olan arrayleri ayır

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [84]:
a,b,c = np.split(x, [3,5])

In [85]:
a

array([1, 2, 3])

In [86]:
b

array([99, 99])

In [87]:
c

array([3, 2, 1])

### İki boyutlu ayırma

In [88]:
m = np.arange(16).reshape(4,4)

In [89]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [91]:
ust, alt = np.vsplit(m, [2])

In [92]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [93]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [96]:
sag, sol = np.hsplit(m,[2])

In [97]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [98]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Sıralama (Sorting)

In [99]:
import numpy as np

In [100]:
v = np.array([2,1,4,3,5])

In [101]:
v

array([2, 1, 4, 3, 5])

In [102]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [103]:
v

array([2, 1, 4, 3, 5])

In [104]:
v.sort()

In [105]:
v

array([1, 2, 3, 4, 5])

np.sort(v), sort metodu, numpy'ın içerisinden çağırıldığında veri setinin ortajinal yapısını bozmadı.
Eğer biz sıralanmış yöntemini kullanmak istersek **yeniden atama** yöntemiyle kullanabiliriz.

v.sort() fonksiyonu v nin yapısını bozmuş oldu. 

In [107]:
# iki boyutlu array siralama

In [110]:
m = np.random.normal(20,5 , (3,3))

In [111]:
m

array([[19.10382114, 17.90207181, 15.60421162],
       [27.40092578,  7.7515947 , 22.33864445],
       [ 5.35316166, 26.57178411, 23.76979085]])

In [113]:
np.sort(m, axis = 1) # her bir satırı kendi içerisinde küçükten büyüğe sıralamıştır.

array([[15.60421162, 17.90207181, 19.10382114],
       [ 7.7515947 , 22.33864445, 27.40092578],
       [ 5.35316166, 23.76979085, 26.57178411]])

In [115]:
np.sort(m, axis = 0) # her bir sütunu kendi içerisinde küçükten büyüğe sıralamıştır.

array([[ 5.35316166,  7.7515947 , 15.60421162],
       [19.10382114, 17.90207181, 22.33864445],
       [27.40092578, 26.57178411, 23.76979085]])

Bilgiler:
- NumPy array'in boyut bilgisini **shape** metodu verir.
- NumPy array'in boyut sayısını **ndim** metodu verir.
- NumPy array'in toplam eleman sayısını **size** metodu verir.
- NumPy array'in veri tipi bilgisini **dtype** metodu verir.

import numpy as np

In [118]:
np.random.randint(10, size = (3,3,2))

array([[[4, 0],
        [9, 1],
        [6, 5]],

       [[3, 0],
        [2, 5],
        [1, 3]],

       [[1, 1],
        [6, 7],
        [4, 0]]])

---

## Index ile Elemana Erişmek

In [136]:
import numpy as np 
a = np.random.randint(10, size = 10)
a

array([1, 7, 2, 2, 5, 5, 8, 8, 4, 4])

In [137]:
a[0] # klasik kullanım

1

In [138]:
a[0] = 100

In [140]:
a

array([100,   7,   2,   2,   5,   5,   8,   8,   4,   4])

In [141]:
m = np.random.randint(10, size = (3,5))
m

array([[7, 3, 6, 0, 8],
       [3, 3, 4, 7, 4],
       [8, 5, 2, 3, 7]])

In [142]:
m[0,0]

7

In [143]:
m[1,1]

3

In [144]:
m[1,4]

4

In [145]:
m[1, 4] = 99

In [146]:
m

array([[ 7,  3,  6,  0,  8],
       [ 3,  3,  4,  7, 99],
       [ 8,  5,  2,  3,  7]])

In [149]:
m[1,4] = 2.2 # NumPy Arrayler fixed type'tır. 2.2  array int olduğu için 2 olarak alınır.

In [148]:
m

array([[7, 3, 6, 0, 8],
       [3, 3, 4, 7, 2],
       [8, 5, 2, 3, 7]])

## Array Alt Küme İşlemleri(Slicing)

In [150]:
import numpy as np

In [152]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [153]:
a[0:3]

array([20, 21, 22])

In [154]:
a[:3]

array([20, 21, 22])

In [155]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [157]:
a[1::2]  # 2. : işaretinden sonra seçilecek sayıların amacı indeksleri kaçar kaçar atlayacağını belirtmektir.

array([21, 23, 25, 27, 29])

In [158]:
a[0::2]

array([20, 22, 24, 26, 28])

In [159]:
a[0::3]

array([20, 23, 26, 29])

In [160]:
# İki boyutlu slice işlemleri

In [161]:
m = np.random.randint(10, size = (5,5))

In [162]:
m

array([[5, 3, 8, 1, 9],
       [3, 5, 3, 8, 9],
       [2, 5, 2, 8, 8],
       [2, 7, 2, 5, 7],
       [0, 3, 3, 7, 0]])

In [164]:
m[:,0] # Bütün satırlar arasından, 0. sütunu seç.

array([5, 3, 2, 2, 0])

In [165]:
m[:,1]

array([3, 5, 5, 7, 3])

In [167]:
m[0,:] # Tüm sütunlar arasından 0. satır.

array([5, 3, 8, 1, 9])

In [169]:
m[0] # 0. satır olarak algılar.

array([5, 3, 8, 1, 9])

In [170]:
m[0:2, 0:3]

array([[5, 3, 8],
       [3, 5, 3]])

In [171]:
m[::,:2]

array([[5, 3],
       [3, 5],
       [2, 5],
       [2, 7],
       [0, 3]])

In [172]:
m[1:3, 0:2]

array([[3, 5],
       [2, 5]])

## Alt Küme Üzerinde İşlem Yapmak

In [174]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[4, 6, 6, 2, 5],
       [5, 1, 9, 2, 4],
       [5, 3, 9, 5, 7],
       [4, 2, 7, 4, 7],
       [8, 0, 6, 4, 2]])

Bir array'in alt kümesine eriştikten sonra isimlendirip kaydettiğimizi düşünelim, bu kaydetmiş olduğumuz isimlendirme üzerine bir değişiklik yaptığımızda array'in ilk halinde de değişiklik olmakta. Fakat bazen seçilen arrayin alt kümesi üzerinde, o alt kümeye özel işlemler yapılmak istenebilir. Bu durumda **alt kümeleri bağımsızlaştırmak** denilen bir işlem yaparız.

In [175]:
alt_a = a[0:3,0:2]

In [176]:
alt_a

array([[4, 6],
       [5, 1],
       [5, 3]])

In [179]:
alt_a[0,0] = 99
alt_a[1,1] = 888

In [180]:
a

array([[ 99,   6,   6,   2,   5],
       [  5, 888,   9,   2,   4],
       [  5,   3,   9,   5,   7],
       [  4,   2,   7,   4,   7],
       [  8,   0,   6,   4,   2]])

In [181]:
m = np.random.randint(10, size = (5,5))
m

array([[8, 8, 4, 6, 3],
       [3, 0, 8, 2, 4],
       [4, 6, 9, 4, 9],
       [7, 1, 0, 7, 5],
       [7, 4, 1, 0, 3]])

In [183]:
alt_b = m[0:3,0:2].copy()
alt_b

array([[8, 8],
       [3, 0],
       [4, 6]])

In [184]:
alt_b[0,0] = 999

In [185]:
alt_b

array([[999,   8],
       [  3,   0],
       [  4,   6]])

In [186]:
m

array([[8, 8, 4, 6, 3],
       [3, 0, 8, 2, 4],
       [4, 6, 9, 4, 9],
       [7, 1, 0, 7, 5],
       [7, 4, 1, 0, 3]])

## Fancy Index ile Elemanlara Erişmek

Fancy Index kavramı ileride en önemli anlamlardan biri olacak. Pandas'da ve NumPy'da Daha ileri düzey eleman seçme kabiliyeti verir.

In [187]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [188]:
v[1]

3

In [189]:
v[3]

9

In [190]:
v[5]

15

In [191]:
[v[1], v[3], v[5]]

[3, 9, 15]

Elimizde onlarca, belki yüzlerce, binlerce index olduğunda bu index değerlerini 1 kerede sorgulama işlemlerini nasıl yapıyoruz?

In [192]:
al_getir = [1,3,5]

In [193]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [195]:
v[al_getir] # 1. 3. 5. indeksi getirdi. Buna Fancy Index denir.

array([ 3,  9, 15])

In [196]:
# İki boyutta fancy

In [197]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [199]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [200]:
m[satir, sutun]

array([1, 5])

In [201]:
# Basit İndex ile fancy index

In [202]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [203]:
m[0, [1,2]]

array([1, 2])

In [206]:
# slice ile fancy

In [205]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

---

## KOŞULLU ELEMAN İŞLEMLERİ
Belirli bir array veya matrisde, belirli koşulları sağlayan elemanlar.

In [1]:
import numpy as np
v = np.array([1,2,3,4,5])

In [2]:
v < 3

array([ True,  True, False, False, False])

In [4]:
v[v < 3] # fancy index

array([1, 2])

In [5]:
v[v > 3]

array([4, 5])

In [6]:
v[v >= 3]

array([3, 4, 5])

In [7]:
v[v <= 3]

array([1, 2, 3])

In [8]:
v[v == 3]

array([3])

In [9]:
v[v != 3]

array([1, 2, 4, 5])

In [10]:
v

array([1, 2, 3, 4, 5])

In [11]:
v*2

array([ 2,  4,  6,  8, 10])

In [12]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [13]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [14]:
v**2

array([ 1,  4,  9, 16, 25])

## MATEMATİKSEL İŞLEMLER

In [15]:
import numpy as np
v = np.array([1,2,3,4,5])

In [16]:
v - 1

array([0, 1, 2, 3, 4])

In [17]:
v * 5

array([ 5, 10, 15, 20, 25])

In [18]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

### ufunc 
- ufuncs "Evrensel Fonksiyonlar" anlamına gelir ve ndarray nesnesi üzerinde çalışan NumPy fonksiyonlarıdır.
- ufuncs, NumPy'de elemanlar üzerinde yinelemeden çok daha hızlı olan vektörleştirmeyi uygulamak için kullanılır. Ayrıca yayın ve hesaplama için çok yararlı olan reduce, accumulate vb. gibi ek yöntemler sağlarlar.
- Biz matematiksel operatörleri kullanıp işlemler yapsakta, arka tarafta numpy içerisinde tanımlanmış spesifik fonksiyonlar çalıştırılır. 

In [ ]:
np.subtract(v, 1) # v - 1

In [25]:
np.add(v, 1) # v + 1

array([2, 3, 4, 5, 6])

In [26]:
np.multiply(v , 4) # v * 4

array([ 4,  8, 12, 16, 20])

In [27]:
np.divide(v, 3) # v / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [28]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [30]:
np.power(v, 3) # v**3

array([  1,   8,  27,  64, 125], dtype=int32)

v % 2

In [32]:
np.mod(v,2) # v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [34]:
np.absolute(np.array([-3])) # |v| mutlak değer

array([3])

In [35]:
np.sin(360)

0.9589157234143065

In [36]:
np.cos(180)

-0.5984600690578581

In [37]:
v = np.array([1,2,3])

In [38]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [39]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [40]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [41]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\tahaa\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\tahaa\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [42]:
# cheatsheetlere bakın

## NumPy ile iki Bilinmeyenli Denklem Çözümü

In [45]:
import numpy as np

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

In [47]:
# Bilinmeyen ifadeleri katsayılarını bir vektöre koy, sonuçları bir vektöre koy.
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [48]:
a

array([[5, 1],
       [1, 3]])

In [49]:
b

array([12, 10])

In [50]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

---

# PANDAS GİRİŞ

- Panel Data'nın kısaltılmasıdır.
- NumPy'ın özelliklerini kullanan ve bunları genişleten bir kütüphanedir.
- NumPy'dan farklı olarak Yapısal veri setleriyle, daha esnek bir çalışma ortamı sağlar.
- Pandas sık kullandığımız veri tipi içerisinde, daha farklı veri tipleriyle de çalışabiliyoruz. Kategorik değişkenler ve sürekli değişkenlerle çalışabiliyoruz.(Fixed Type değil)
- Pandas temelinde ekonomik ve finansal verilerle çalışmak için doğmuştur. Panel veri, Zaman serisi çalışmaları için doğmuştur. Panel verisi: Kesit veri ve Zaman serisi verisinin bir arada olduğu veri tipidir. Bu durumda klasik veri tutma yaklaşımları yerine **zaman** indeksini daha fazla önemseyen bir veri tutma söz konusudur.
- Veri manipülasyonu ve veri analizi için yazılmış açık kaynak kodlu bir Python kütüphanesidir.
- R DataFrame yapısını Python dünyasına taşımış ve DataFrame'ler üzerinde hızlı ve etkili çalışabilme imkanı sağlamıştır.

## Pandas Serisi Oluşturmak

- Pandas kütüphanesi kapsamında, ele alacak olduğumuz ana veri tipimiz Pandas DataFrameler olacak.
Yine de Pandas serilerini öğrenmiş olacağız.
- Pandas arraylerin, numpy arraylerinden farklı olarak indeks bilgileri de tutulur.

In [3]:
import pandas as pd

In [5]:
pd.Series([16,53,3,4,5])

0    16
1    53
2     3
3     4
4     5
dtype: int64

Pandas Arrayler'de değerler, indeksleriyle beraber tutulur. İndeks ifadeleri internal(içsel) bir şekilde veri tipinin içerisinde tutulmaktadır. Ayrı bir bileşendir.

In [6]:
seri = pd.Series([16,53,3,4,5])

In [7]:
type(seri)

pandas.core.series.Series

In [8]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [9]:
seri.dtype

dtype('int64')

In [10]:
seri.size

5

In [11]:
seri.ndim

1

In [13]:
seri.values # array formunda sadece değer bilgileri verilir

array([16, 53,  3,  4,  5], dtype=int64)

In [16]:
seri.head(3) # Serinin, ilk kaç tane gözlemine bakılmak istenirse parantez içerisinde yazılır.

0    16
1    53
2     3
dtype: int64

In [18]:
seri.tail(3) # Serinin, sondan kaç tane gözlemine bakılmak istenirse parantez içerisinde yazılır.

2    3
3    4
4    5
dtype: int64

In [19]:
# İndex isimlendirmesi

In [23]:
pd.Series([123,42,534,32,12], index = [1,3,5,7,9]) # indekslerin isimlendirmesini kendimiz yapabiliriz.

1    123
3     42
5    534
7     32
9     12
dtype: int64

In [26]:
pd.Series([123,42,534,32,12], index = ["a","b","c","d","e"]) # indekslerin isimlendirmesini string değerler 
                                                             # ile de yapabiliriz.

a    123
b     42
c    534
d     32
e     12
dtype: int64

In [42]:
seri = pd.Series([123,42,534,32,12], index = ["a","b","c","d","e"]) # sözlük yapısına benzerdir.

In [43]:
seri["a"]

123

In [44]:
seri["a":"c"] # slice işlemleri

a    123
b     42
c    534
dtype: int64

In [34]:
# sözlük üzerinden liste oluşturmak

In [35]:
sozluk = pd.Series({"reg":10, "log":11, "cart": 12})

In [36]:
sozluk

reg     10
log     11
cart    12
dtype: int64

In [47]:
sozluk = {"reg":10, "log":11, "cart": 12} # sözlük yapısı

In [48]:
seri = pd.Series(sozluk)

In [49]:
seri

reg     10
log     11
cart    12
dtype: int64

In [50]:
# İki seriyi birleştirerek seri oluşturma

In [53]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

## ELEMAN İŞLEMLERİ

In [1]:
import numpy as np
import pandas as pd
a = np.array([11,22,33,44,55])
seri = pd.Series(a)
seri

0    11
1    22
2    33
3    44
4    55
dtype: int32

In [2]:
seri[0]

11

In [3]:
seri[0:3]

0    11
1    22
2    33
dtype: int32

In [4]:
seri = pd.Series([121,200,150,99], index = ["reg","loj","cart","rf"])

In [5]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [6]:
seri.index # sadece index değerlerine erişebiliriz

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [7]:
seri.keys # sadece keys değerlerine erişebiliriz

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [8]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [10]:
seri.values # sadece values değerlerine erişebiliriz

array([121, 200, 150,  99], dtype=int64)

In [11]:
# eleman sorgulama

In [12]:
"reg" in seri

True

In [14]:
"a" in seri

False

In [15]:
seri["reg"]

121

In [16]:
# Fancy Eleman

In [17]:
seri[["rf", "reg"]]

rf      99
reg    121
dtype: int64

In [20]:
seri["reg"] = 130 # yeniden atama yöntemi

In [21]:
seri["reg"]

130

In [23]:
seri["reg":"cart"]

reg     130
loj     200
cart    150
dtype: int64

## PANDAS DATAFRAME OLUŞTURMA

- Yapısal bir veri tipidir. Excel veri yapısına benzerdir.
- Kategorik ve yapısal veri tiplerini bir arada tutabilir. Fixed Type değildir.
- Daha analitik anlamda, makine öğrenmesi modellerine verecek olduğumuz datasetleri gibi düşünebiliriz.

In [24]:
import pandas as pd

In [25]:
l = [1,2,39,67,90]
l

[1, 2, 39, 67, 90]

In [27]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [28]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
pd.DataFrame(m, columns = ["var1","var2","var3"]) # iki boyutlu data frame oluşturduk.

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [31]:
# df isimlendirme

In [33]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [35]:
df.columns = ("deg1","deg2","deg3")

In [36]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [37]:
type(df)

pandas.core.frame.DataFrame

In [39]:
df.axes # satır ve sütun bilgilerini verir

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [41]:
df.shape

(3, 3)

In [42]:
df.ndim

2

In [43]:
df.size

9

In [46]:
df.values # data frame tipinden değerleri çekip, numpy array nesnesine çevirir

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
type(df.values)

numpy.ndarray

In [47]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [49]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [50]:
a = np.array([1,2,3,4,5])

In [51]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

## PANDAS DATAFRAME ELEMAN İŞLEMLERİ

In [72]:
import numpy as np
import pandas as pd
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [105]:
# sözlük üzerinden dataframe oluşturmak

In [74]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [75]:
sozluk

{'var1': array([6, 7, 6, 8, 5]),
 'var2': array([5, 6, 1, 9, 8]),
 'var3': array([1, 8, 2, 7, 4])}

In [76]:
df = pd.DataFrame(sozluk)

In [77]:
df

var1  var2  var3
0     6     5     1
1     7     6     8
2     6     1     2
3     8     9     7
4     5     8     4

In [78]:
df[0:1]

var1  var2  var3
0     6     5     1

In [79]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [80]:
df.index = ["a","b","c","d","e"]

In [81]:
df

var1  var2  var3
a     6     5     1
b     7     6     8
c     6     1     2
d     8     9     7
e     5     8     4

In [82]:
df["c":"e"]

var1  var2  var3
c     6     1     2
d     8     9     7
e     5     8     4

In [83]:
#silme işlemi

In [84]:
df.drop("a", axis = 0) # axis, satır bilgisi verir

var1  var2  var3
b     7     6     8
c     6     1     2
d     8     9     7
e     5     8     4

In [85]:
df # Veri setinin anayapısı üzerinde bir değişiklik olmadı.

var1  var2  var3
a     6     5     1
b     7     6     8
c     6     1     2
d     8     9     7
e     5     8     4

In [86]:
df.drop("a", axis = 0, inplace = True) # inplace, DataFrame üzerinde yapılan değişikliğin 
                                       # kalıcı olmasını sağlar.

In [87]:
df

var1  var2  var3
b     7     6     8
c     6     1     2
d     8     9     7
e     5     8     4

In [88]:
# fancy ile silme işlemi

In [89]:
l = ["c","e"]

In [90]:
df.drop(l, axis = 0, inplace = True)

In [91]:
df

var1  var2  var3
b     7     6     8
d     8     9     7

In [92]:
# Değişkenler için

In [93]:
"var1" in df

True

In [94]:
l = ["var1", "var4", "var2"]

In [95]:
for i in l:
    print(i in df)

True
False
True


In [96]:
df

var1  var2  var3
b     7     6     8
d     8     9     7

In [97]:
df["var4"] = df["var1"] / df["var2"] # var4 diye bir değişken olmadığı için atama işlemi 
                                     # yaptığımızda bunu yeni sütun oluşturmak olarak anlar.

In [98]:
df

var1  var2  var3      var4
b     7     6     8  1.166667
d     8     9     7  0.888889

In [99]:
# defisken silmek

In [100]:
df.drop("var4", axis = 1) # Sütunları bu şekilde sileriz

var1  var2  var3
b     7     6     8
d     8     9     7

In [101]:
df.drop("var4", axis = 1, inplace = True)

In [102]:
df

var1  var2  var3
b     7     6     8
d     8     9     7

In [103]:
l = ["var1", "var2"]

In [104]:
df.drop(l, axis = 1)

var3
b     8
d     7

## GÖZLEM VE DEĞİŞKEN SEÇİMİ (loc & iloc)

In [3]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"]) # değişken isimleri var1 var2 var3
df

var1  var2  var3
0    20    16     8
1    27    14     1
2    15    21     1
3    11    29     3
4    22    13    18
5    16     7     8
6    23    18     6
7    25     7     7
8    20     2    15
9    22    29     2

In [4]:
# loc: tanımlandığı şekliyle seçim yapmak için kullanılır.

In [9]:
df.loc[0:3] # 3 dahil

var1  var2  var3
0    20    16     8
1    27    14     1
2    15    21     1
3    11    29     3

In [6]:
# iloc: alışık olduğumuz indexleme mantığıyla seçim yapar.

In [10]:
df.iloc[0:3] # 3 dahil değil

var1  var2  var3
0    20    16     8
1    27    14     1
2    15    21     1

In [11]:
df.iloc[0,0]

20

In [12]:
df.iloc[:3,:2]

var1  var2
0    20    16
1    27    14
2    15    21

In [13]:
df.loc[0:3, "var3"]

0    8
1    1
2    1
3    3
Name: var3, dtype: int32

In [16]:
df.iloc[0:3, "var3"] # ValueError: Değişken yada gözlem birimleri(satırlar) ile ilgili mutlak 
                     # bir değer işaretlemesi yapacaksak "loc" u kullanmamız gerekiyor. Kısacası değişken 
                     # isimleri veya gözlem birilerine (index isimlerine) göre işlem yapmak istersek loc'u
                     # tercih etmeliyiz.

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [17]:
df.iloc[0:3]["var3"]

0    8
1    1
2    1
Name: var3, dtype: int32

- Eğer verilen kurallara bağlı bir şekilde, seçim yapılma ihtiyacı varsa loc yapısı kullanılır.
- Eğer verilen isimlendirmelerden bağımsız, klasik index mantığı ile seçim yapmak istiyorum deniyorsa
iloc yapısı kullanılır.

## KOŞULLU ELEMAN İŞLEMLERİ

In [19]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df

var1  var2  var3
0    22    24     1
1     1    21     3
2     5    28     3
3     6    22    18
4    26     7    21
5    13     4    16
6    11    27     7
7    29    18    27
8     2    13     1
9    27    17    14

In [20]:
df["var1"]

0    22
1     1
2     5
3     6
4    26
5    13
6    11
7    29
8     2
9    27
Name: var1, dtype: int32

In [21]:
df["var1"][0:1]

0    22
Name: var1, dtype: int32

In [22]:
df[0:2]

var1  var2  var3
0    22    24     1
1     1    21     3

In [25]:
df[0:2][["var1","var2"]] # tek [] ile yaparsak hata alırız. Sadece fancy yardımıyla istediğimizi elde ederiz.

var1  var2
0    22    24
1     1    21

In [26]:
df

var1  var2  var3
0    22    24     1
1     1    21     3
2     5    28     3
3     6    22    18
4    26     7    21
5    13     4    16
6    11    27     7
7    29    18    27
8     2    13     1
9    27    17    14

In [27]:
df.var1

0    22
1     1
2     5
3     6
4    26
5    13
6    11
7    29
8     2
9    27
Name: var1, dtype: int32

In [30]:
df[df.var1 > 15] # DataFrame içerisinde, var1 sütundaki 15'ten büyük verileri filtreledi.

var1  var2  var3
0    22    24     1
4    26     7    21
7    29    18    27
9    27    17    14

In [33]:
df[df.var1 > 15]["var2"] # DataFrame içerisinde, var1 sütundaki 15'ten büyük verileri 
                         # filtreledi ve var2 sütununu yazdırdı.

0    24
4     7
7    18
9    17
Name: var2, dtype: int32

In [35]:
df[(df.var1 > 15) & (df.var3 < 5)]

var1  var2  var3
0    22    24     1

In [39]:
df.loc[(df.var1 > 15), ["var1","var2"]] # Var1 ve var2 sürunlarında var1 in 15ten büyük olduğu satırlar.

var1  var2
0    22    24
4    26     7
7    29    18
9    27    17

In [38]:
df[(df.var1 > 15)]["var1"]

0    22
4    26
7    29
9    27
Name: var1, dtype: int32

In [40]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
0    22    24
4    26     7
7    29    18
9    27    17

## BİRLEŞTİRME İŞLEMLERİ

In [43]:
import numpy as np
import pandas as pd
m = np.random.randint(1, 30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    17    27     8
1    13    19    23
2    22    17    24
3     5    17    16
4     3    26    23

In [44]:
df2 = df1 + 99

In [45]:
df2

var1  var2  var3
0   116   126   107
1   112   118   122
2   121   116   123
3   104   116   115
4   102   125   122

In [47]:
pd.concat([df1,df2]) # Birleştirme işlemi

var1  var2  var3
0    17    27     8
1    13    19    23
2    22    17    24
3     5    17    16
4     3    26    23
0   116   126   107
1   112   118   122
2   121   116   123
3   104   116   115
4   102   125   122

In [49]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which ca

In [52]:
pd.concat([df1,df2], ignore_index = True) #İndex problemi ortadan kalktı.

var1  var2  var3
0    17    27     8
1    13    19    23
2    22    17    24
3     5    17    16
4     3    26    23
5   116   126   107
6   112   118   122
7   121   116   123
8   104   116   115
9   102   125   122

In [54]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [56]:
df2.columns = ["var1","var2","deg3"]

In [57]:
df2

var1  var2  deg3
0   116   126   107
1   112   118   122
2   121   116   123
3   104   116   115
4   102   125   122

In [58]:
df1

var1  var2  var3
0    17    27     8
1    13    19    23
2    22    17    24
3     5    17    16
4     3    26    23

In [59]:
pd.concat([df1,df2], ignore_index = True)

var1  var2  var3   deg3
0    17    27   8.0    NaN
1    13    19  23.0    NaN
2    22    17  24.0    NaN
3     5    17  16.0    NaN
4     3    26  23.0    NaN
5   116   126   NaN  107.0
6   112   118   NaN  122.0
7   121   116   NaN  123.0
8   104   116   NaN  115.0
9   102   125   NaN  122.0

In [67]:
pd.concat([df1,df2], join = "inner", ignore_index = True) # kesişimlerine göre birleştirdi

var1  var2
0    17    27
1    13    19
2    22    17
3     5    17
4     3    26
5   116   126
6   112   118
7   121   116
8   104   116
9   102   125

In [72]:
pd.concat([df1,df2], join = 'outer', ignore_index = True)

var1  var2  var3   deg3
0    17    27   8.0    NaN
1    13    19  23.0    NaN
2    22    17  24.0    NaN
3     5    17  16.0    NaN
4     3    26  23.0    NaN
5   116   126   NaN  107.0
6   112   118   NaN  122.0
7   121   116   NaN  123.0
8   104   116   NaN  115.0
9   102   125   NaN  122.0

## İLERİ BİRLEŞTİRME İŞLEMLERİ

In [2]:
import pandas as pd

In [3]:
# birebir birleştirme

In [31]:
df1 = pd.DataFrame({'calisanlar': ['Ali','Veli','Ayse','Fatma'],
                   'grup': ['Muhasebe','Muhendislik','Muhendislik','İK']})

df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [5]:
df2 = pd.DataFrame({'calisanlar': ['Ayse','Ali','Veli','Fatma'],
                   'ilk_giris':[2010,2009,2014,2019]})

df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

- Birebir birleştirme: Tüm elemanların iki veri setinde de aynen yer alması durumudur.

In [6]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [7]:
pd.merge(df1,df2, on = "calisanlar") # çalışanlar üstünden birleştir

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [8]:
# coktan teke - many to one

In [9]:
df3 = pd.merge(df1, df2)

In [10]:
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [12]:
df4 = pd.DataFrame({'grup': ['Muhasebe','Muhendislik','İK'],
                   'mudur': ['Caner','Mustafa','Berkcan']})

df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [14]:
pd.merge(df3,df4) 

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [15]:
# coktan coka - many to many

In [16]:
df5 = pd.DataFrame({'grup': ['Muhasebe','Muhasebe','Muhendislik','Muhendislik','İK','İK'],
                   'yetenekler': ['matematik','excel','kodlama','linux','excel','yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [17]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [19]:
pd.merge(df1, df5) # df1'de tüm çalışanlar tekildi. df5 le birlikte çokladı. Ve yetenekler eklendi.

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

## TOPLULAŞTIRMA VE GRUPLAMA (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:
- count()
- first()
- last()
- mean()
- median()
- min()
- max()
- std()
- var()
- sum()

### Toplulaştırma (Aggregation)

In [33]:
import seaborn as sns # Bu kütüphanenin içerisinde bazı veri setleri var

In [35]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [36]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [46]:
df.shape # Veri setinin boyut bilgisi.

(1035, 6)

In [47]:
df["mass"].mean() # Veri setinin mass sütunundaki değerlerin ortalamasını hesapla.

2.6381605847953216

In [48]:
df["mass"].count() # Veri setinin mass sütunundaki kaç değer var.

513

In [49]:
df["mass"].min() # Veri setinin mass sütunundaki değerlerin en küçüğünü bul.

0.0036

In [50]:
df["mass"].max() # Veri setinin mass sütunundaki değerlerin en büyüğünü bul.

25.0

In [51]:
df["mass"].sum() # Veri setinin mass sütunundaki değerlerin toplamını hesapla.

1353.37638

In [52]:
df["mass"].std() # Veri setinin mass sütunundaki değerlerin standart sapmasını hesapla.

3.8186166509616046

In [55]:
df["mass"].var() # Veri setinin mass sütunundaki değerlerin varyansını hesapla.

14.58183312700122

In [57]:
df.describe() # Veri setindeki tüm değişkenleri, betimsel istatistikleri anlamında ortaya koyabiliyoruz

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [58]:
df.describe().T # Transpozunu al - Devir

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [59]:
df.dropna().describe().T # Veri setinin içerisindeki eksik değerleri sildi ve buna göre betimsel 
                         # istatistikleri hesapladı.

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

### Gruplama İşlemleri(Grouping)

In [61]:
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                  'veri': [10,11,52,23,43,55]}, columns = ['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

Gruplama İşlemleri: Veri setinde yer alan kategorik değişkenlerin, gruplarının yakalanmasının ve bu grupların özelinde bazı işlemler yapılması.

In [64]:
df.groupby("gruplar") # gruplar sütunundaki A, B ve C sınıflarını tuttu.

In [65]:
df.groupby("gruplar").mean() # Tuttuğu sınıfların ortalama değerini hesapladı.

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [66]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [67]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

method, bir kategorik değişkendir. gruplama yapabilmek adına bizlere bir kategorik değişken gerekli ki sınıflarına gidip, o sınıflara özel bazı işlemler yapabilelim.

In [69]:
df.groupby("method") # bu sütunda kaç tane farklı(unique, eşsiz) sınıf varsa yakalandı.

In [71]:
df.groupby("method")["orbital_period"] # değişkeni de seçtik

In [72]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [73]:
df.groupby("method")["mass"].mean()

method
Astrometry                            NaN
Eclipse Timing Variations        5.125000
Imaging                               NaN
Microlensing                          NaN
Orbital Brightness Modulation         NaN
Pulsar Timing                         NaN
Pulsation Timing Variations           NaN
Radial Velocity                  2.630699
Transit                          1.470000
Transit Timing Variations             NaN
Name: mass, dtype: float64

In [74]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

In [76]:
df.dropna().groupby("method")["orbital_period"].describe()

count        mean          std      min       25%        50%  \
method                                                                          
Radial Velocity  497.0  837.454878  1470.131725  1.32830  39.02600  358.00000   
Transit            1.0    2.703390          NaN  2.70339   2.70339    2.70339   

                        75%          max  
method                                    
Radial Velocity  1001.70000  17337.50000  
Transit             2.70339      2.70339

## İLERİ TOPLULAŞTIRMA İŞLEMLERİ (AGGREGATE,FİLTER,TRANSFORM,APPLY)

### AGGREGATE

In [83]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                 columns = ['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [102]:
# aggregate: Veri setimizdeki birden fazla satırı özetlemek ve tek bir sonuç elde etmek için kullanılır.
# Genellikle groupby ile birlikte kullanılarak, gruplara ayrılmış verilere uygulanır.

In [89]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [101]:
df.groupby("gruplar").aggregate(["min", "median", "max"]) # kendim özel bir istatistik belirtmek istiyorum 
                                                          # dediğimizde aggregate ile bunu başarabiliriz.
# Pandas'ın son sürümlerinde, NumPy fonksiyonlarını doğrudan kullanabilirsiniz,
# ancak bunları string olarak belirtmeniz gerekiyor.

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [98]:
df.groupby("gruplar").aggregate({"degisken1": "min", "degisken2": "max"})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

### FİLTER

- Filter, DataFrame satırları veya sütunları belirli kriterlere göre seçmek için kullanılan güçlü bir araçtır.
- Hem basit hem de karmaşık koşullar için kullanılabilir.

In [103]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                 columns = ['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

Kendi kişisel fonksiyonlarımızı, bir filtreleme aracı olarak değişkenlerin üzerinde sorgulamak işlemini
**filter** işlemi ile ele almış olacağız.

In [104]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [106]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [105]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

### APPLY 

In [15]:
import numpy as np
import pandas as pd
df = pd.DataFrame({
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                 columns = ['degisken1','degisken2'])
df

degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [17]:
df.apply(np.sum)

degisken1     198
degisken2    2028
dtype: int64

In [19]:
df.apply(np.mean)

degisken1     33.0
degisken2    338.0
dtype: float64

In [21]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                 columns = ['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [27]:
df.groupby("gruplar").apply(np.mean)

gruplar
A     98.5
B     99.5
C    358.5
dtype: float64

### PİVOT TABLOLAR

groupby'ın çok boyutlusu olarak düşünülebilir.

In [2]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
titanic.groupby("sex")[["survived"]].mean() # pivot işlemleri 
# İki tane köşeli parantez içerisinde istediğimiz verinin sütun adını yazarsak, Data Frame'e dönüşür.

survived
sex             
female  0.742038
male    0.188908

In [8]:
titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean").unstack()
#unstack fonksiyonu, genellikle çok seviyeli(multi-level) indekslere sahip DataFrameleri yeniden 
# şekillendirmek için kullanılır. Pivot tablolar (Maliyet etkin tablolar diyebiliriz)

C:\Users\tahaa\AppData\Local\Temp\ipykernel_17072\4141779808.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean").unstack()


survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [10]:
titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean")

C:\Users\tahaa\AppData\Local\Temp\ipykernel_17072\1052603086.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex", "class"])[["survived"]].aggregate("mean")


survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [12]:
# Pivot ile Pivot table

In [14]:
titanic.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [16]:
titanic.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [18]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [22]:
titanic.pivot_table("survived", ["sex",age], "class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

## DIŞ KAYNAKLI VERİ OKUMAK

In [25]:
import pandas as pd

In [27]:
pd.read_csv("reading_data/ornekcsv.csv")

a;b;c
0    78;12;1
1    78;12;2
2   78;324;3
3      7;2;4
4    88;23;5
5       6;2;
6    56;11;6
7     7;12;7
8    56;21;7
9    346;2;8
10     5;1;8
11  456;21;8
12   3;12;88

Ayraç olarak ön tanımlı değer virgül(,) olduğundan ve bizim datasetimizi ayraç olarak noktalı virgül(;) kullandığından dolayı yamuk yumuk bir görselleştirme aldık. Bunu düzeltelim.

In [38]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'list[HashableT] | Callable[[Hashable], bool] | None' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Sequence[str] | Mapping[str, Sequence[str]] | None' = None,
    keep_default_na: 'bool' = True,
    n

In [42]:
# csv okumak
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [44]:
# txt okumak
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [46]:
# xlsx okumak
pd.read_excel("reading_data/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [48]:
df = pd.read_excel("reading_data/ornekx.xlsx")

In [50]:
type(df)

pandas.core.frame.DataFrame

In [52]:
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [54]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [56]:
df.columns = ("A","B","C")

In [60]:
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [67]:
# sıfırdan txt okuma
tips = pd.read_csv("data.txt")

In [69]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [75]:
tips2 = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [77]:
tips2.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [79]:
type(tips2)

pandas.core.frame.DataFrame